spring:
  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    user: ${spring-datasource-username}
    url: ${spring-datasource-url}
    password: ${spring-datasource-password}
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial DB migration
    locations: classpath:db/migrations,classpath:sit


azure:
  keyvault:
    client-id: f901ea97-9a8e-4b2b-97f8-ae75b7928a1f
    client-key: O4-I8~ir5s.eE_tBvtAO6--SvKuhZ7Ihyf
    tenant-id: 05d75c05-fa1a-42e7-9cf1-eb416c396f2d
    uri: https://cmdsitkeyvault.vault.azure.net/
    enabled: true