## Github action workflow for cloud data ingestion
name: Cloud Data Ingestion Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Script Change description'
        required: true
      env:
        description: "Data Ingestion Environment(DEV/SIT/PP/PROD)"        
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: ${{github.event.inputs.env}}

    steps:
    - name : Git checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn spring-boot:run -Dspring-boot.run.profiles=${{github.event.inputs.env}}

